/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Header that contains the headers for which Rust UAPI bindings
 * will be automatically generated by `bindgen`.
 *
 * Sorted alphabetically.
 */

#include <uapi/asm-generic/ioctl.h>
<<<<<<< HEAD
=======
#include <uapi/linux/mdio.h>
>>>>>>> 2d5404caa8 (Linux 6.12-rc7)
#include <uapi/linux/mii.h>
#include <uapi/linux/ethtool.h>
